=== leventekeves/IG9GGV_XMLGyak/XMLTaskIG9GGV/DomParseIG9GGV/XMLSchemaIG9GGV.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="pizzalanc_nyilvantartas">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="pizzalancok">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="pizzalanc" type="pizzalancTipus" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="vezerigazgatok">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="vezerigazgato" type="vezerigazgatoTipus" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="etteremek">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="etterem" type="etteremTipus" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="etelek">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="etel" type="etelTipus" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="alkalmazottak">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="alkalmazott" type="alkalmazottTipus" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="vezetesek">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="vezeti" type="vezetiTipus" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="kaphatok">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="kaphato" type="kaphatoTipus" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		
		<xs:key name="pizzalancPK">
			 <xs:selector xpath="pizzalancok/pizzalanc" /> 
			 <xs:field xpath="@pl_ID" /> 
		</xs:key>
		<xs:key name="vezerigazgatoPK">
			 <xs:selector xpath="vezerigazgatok/vezerigazgato" /> 
			 <xs:field xpath="@vi_ID" /> 
		</xs:key>
		<xs:key name="etteremPK">
			 <xs:selector xpath="etteremek/etterem" /> 
			 <xs:field xpath="@em_ID" /> 
		</xs:key>
		<xs:key name="etelPK">
			 <xs:selector xpath="etelek/etel" /> 
			 <xs:field xpath="@el_ID" /> 
		</xs:key>
		<xs:key name="alkalmazottPK">
			 <xs:selector xpath="alkalmazottak/alkalmazott" /> 
			 <xs:field xpath="@a_ID" /> 
		</xs:key>
		
		<xs:keyref refer="etteremPK" name="etteremFK">
			<xs:selector xpath="kaphatok/kaphato" />
			<xs:field xpath="@em_IDREF" />
		</xs:keyref>
		<xs:keyref refer="etelPK" name="etelFK">
			<xs:selector xpath="kaphatok/kaphato" />
			<xs:field xpath="@el_IDREF" />
		</xs:keyref>
		<xs:keyref refer="pizzalancPK" name="pizzalancFK">
			<xs:selector xpath="vezetesek/vezeti" />
			<xs:field xpath="@pl_IDREF" />
		</xs:keyref>
		<xs:keyref refer="vezerigazgatoPK" name="vezerigazgatoFK">
			<xs:selector xpath="vezetesek/vezeti" />
			<xs:field xpath="@vi_IDREF" />
		</xs:keyref>
		
		<xs:keyref refer="pizzalancPK" name="etteremPizzalancFK">
			<xs:selector xpath="ettermek/etterem" />
			<xs:field xpath="@pl_IDREF" />
		</xs:keyref>
		<xs:keyref refer="etteremPK" name="alkalmazottEtteremFK	">
			<xs:selector xpath="alkalmazottak/alkalmazott" />
			<xs:field xpath="@em_IDREF" />
		</xs:keyref>
		
		<xs:unique name="unique-vezetes-pl">
    		<xs:selector xpath="vezetesek/vezeti"/>
    		<xs:field xpath="@pl_IDREF"/>
   		</xs:unique>
   		<xs:unique name="unique-vezetes-vi">
    		<xs:selector xpath="vezetesek/vezeti"/>
    		<xs:field xpath="@vi_IDREF"/>
   		</xs:unique>
	</xs:element>
	
	<xs:complexType name="pizzalancTipus">
		<xs:sequence>
			<xs:element name="nev" type="xs:string" />
			<xs:element name="alapitas_idopontja" type="xs:date" />
			<xs:element name="tozsden" type="xs:boolean" />
		</xs:sequence>
		<xs:attribute name="pl_ID" type="xs:integer" use="required" />
	</xs:complexType>
	
	<xs:complexType name="vezerigazgatoTipus">
		<xs:sequence>
			<xs:element name="nev" type="xs:string" />
			<xs:element name="szuletesi_datum" type="xs:date" />
			<xs:element name="nem" type="xs:string" />
		</xs:sequence>
		<xs:attribute name="vi_ID" type="xs:integer" use="required" />
	</xs:complexType>
	
	<xs:complexType name="etteremTipus">
		<xs:sequence>
			<xs:element name="cim" type="cimTipus" />
		</xs:sequence>
		<xs:attribute name="em_ID" type="xs:integer" use="required" />
		<xs:attribute name="pl_IDREF" type="xs:integer" use="required" />
	</xs:complexType>
	
	<xs:complexType name="etelTipus">
		<xs:sequence>
			<xs:element name="nev" type="xs:string" />
			<xs:element name="ar" type="xs:integer" />
			<xs:element name="alapanyag" type="xs:string" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="el_ID" type="xs:integer" use="required" />
	</xs:complexType>
	
	<xs:complexType name="alkalmazottTipus">
		<xs:sequence>
			<xs:element name="nev" type="xs:string" />
			<xs:element name="szuletesi_datum" type="xs:date" />
			<xs:element name="fizetes" type="xs:integer" />
		</xs:sequence>
		<xs:attribute name="a_ID" type="xs:integer" use="required" />
		<xs:attribute name="em_IDREF" type="xs:integer" use="required" />
	</xs:complexType>
	
	<xs:complexType name="vezetiTipus">
		<xs:sequence>
			<xs:element name="kinevezes_idopontja" type="xs:date" />
		</xs:sequence>
		<xs:attribute name="pl_IDREF" type="xs:integer" use="required" />
		<xs:attribute name="vi_IDREF" type="xs:integer" use="required" />
	</xs:complexType>
	
	<xs:complexType name="kaphatoTipus">
		<xs:sequence>
			<xs:element name="miota" type="xs:date" />
		</xs:sequence>
		<xs:attribute name="em_IDREF" type="xs:integer" use="required" />
		<xs:attribute name="el_IDREF" type="xs:integer" use="required" />
	</xs:complexType>
	
	<xs:complexType name="cimTipus">
		<xs:sequence>
			<xs:element name="varos" type="xs:string" />
			<xs:element name="utca" type="xs:string" />
			<xs:element name="hazszam" type="xs:integer" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== leventekeves/IG9GGV_XMLGyak/XMLTaskIG9GGV/DomParseIG9GGV/XMLIG9GGV.xml
<?xml version="1.0" encoding="UTF-8"?>

<pizzalanc_nyilvantartas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemaIG9GGV.xsd">
	<pizzalancok >
		<pizzalanc pl_ID="01">
			<nev>McPizza</nev>
			<alapitas_idopontja>1987-11-21</alapitas_idopontja>
			<tozsden>true</tozsden>
		</pizzalanc>
		<pizzalanc pl_ID="02">
			<nev>Pizza King</nev>
			<alapitas_idopontja>1975-07-23</alapitas_idopontja>
			<tozsden>false</tozsden>
		</pizzalanc>
	</pizzalancok>
	
	<vezerigazgatok>
		<vezerigazgato vi_ID="01">
			<nev>Török Vilmos</nev>
			<szuletesi_datum>1984-03-13</szuletesi_datum>
			<nem>Férfi</nem>
		</vezerigazgato>
		<vezerigazgato vi_ID="02">
			<nev>Fekete Ágnes</nev>
			<szuletesi_datum>1974-04-23</szuletesi_datum>
			<nem>Nő</nem>
		</vezerigazgato>
	</vezerigazgatok>
	
	<etteremek>
		<etterem em_ID="01" pl_IDREF="01">
			<cim>
				<varos>Budapest</varos>
				<utca>Nagy út</utca>
				<hazszam>12</hazszam>
			</cim>
		</etterem>
		<etterem em_ID="02" pl_IDREF="01">
			<cim>
				<varos>Debrecen</varos>
				<utca>Kerek út</utca>
				<hazszam>5</hazszam>
			</cim>
		</etterem>
		<etterem em_ID="03" pl_IDREF="02">
			<cim>
				<varos>Budapest</varos>
				<utca>Kis út</utca>
				<hazszam>7</hazszam>
			</cim>
		</etterem>
		<etterem em_ID="04" pl_IDREF="02">
			<cim>
				<varos>Budapest</varos>
				<utca>Nagy tér</utca>
				<hazszam>21</hazszam>
			</cim>
		</etterem>
		<etterem em_ID="05" pl_IDREF="02">
			<cim>
				<varos>Debrecen</varos>
				<utca>Kis tér</utca>
				<hazszam>13</hazszam>
			</cim>
		</etterem>
	</etteremek>
	
	<etelek>
		<etel el_ID="01">
			<nev>Sonkás pizza</nev>
			<ar>1100</ar>
			<alapanyag>Sonka</alapanyag>
			<alapanyag>Sajt</alapanyag>
		</etel>
		<etel el_ID="02">
			<nev>Sonkás-kukoricás pizza</nev>
			<ar>1300</ar>
			<alapanyag>Sonka</alapanyag>
			<alapanyag>Kukorica</alapanyag>
			<alapanyag>Sajt</alapanyag>
		</etel>
		<etel el_ID="03">
			<nev>Szalámis pizza</nev>
			<ar>1600</ar>
			<alapanyag>Szalámi</alapanyag>
			<alapanyag>Sajt</alapanyag>
		</etel>
	</etelek>
	
	<alkalmazottak>
		<alkalmazott a_ID="01" em_IDREF="05">
			<nev>Fekete Balázs</nev>
			<szuletesi_datum>1988-01-12</szuletesi_datum>
			<fizetes>260000</fizetes>
		</alkalmazott>
		<alkalmazott a_ID="02" em_IDREF="04">
			<nev>Balogh Sára</nev>
			<szuletesi_datum>1977-02-22</szuletesi_datum>
			<fizetes>300000</fizetes>
		</alkalmazott>
		<alkalmazott a_ID="03" em_IDREF="05">
			<nev>Csonka Gábor</nev>
			<szuletesi_datum>2001-12-12</szuletesi_datum>
			<fizetes>460000</fizetes>
		</alkalmazott>
		<alkalmazott a_ID="04" em_IDREF="02">
			<nev>Farkas Anita</nev>
			<szuletesi_datum>1999-03-21</szuletesi_datum>
			<fizetes>257000</fizetes>
		</alkalmazott>
		<alkalmazott a_ID="05" em_IDREF="01">
			<nev>Antal Benjamin</nev>
			<szuletesi_datum>1956-11-30</szuletesi_datum>
			<fizetes>310000</fizetes>
		</alkalmazott>
		<alkalmazott a_ID="06" em_IDREF="03">
			<nev>Csonka Ábel</nev>
			<szuletesi_datum>1976-07-11</szuletesi_datum>
			<fizetes>265000</fizetes>
		</alkalmazott>
		<alkalmazott a_ID="07" em_IDREF="03">
			<nev>Vászoly Martina</nev>
			<szuletesi_datum>1987-12-21</szuletesi_datum>
			<fizetes>280000</fizetes>
		</alkalmazott>
		<alkalmazott a_ID="08" em_IDREF="03">
			<nev>Szabó Soma</nev>
			<szuletesi_datum>1994-05-12</szuletesi_datum>
			<fizetes>400000</fizetes>
		</alkalmazott>
	</alkalmazottak>
	
	<vezetesek>
		<vezeti pl_IDREF="01" vi_IDREF="01">
			<kinevezes_idopontja>2015-01-12</kinevezes_idopontja>
		</vezeti>
		<vezeti pl_IDREF="02" vi_IDREF="02">
			<kinevezes_idopontja>2020-10-11</kinevezes_idopontja>
		</vezeti>
	</vezetesek>
	
	<kaphatok>
		<kaphato em_IDREF="01" el_IDREF="01">
			<miota>1987-11-21</miota>
		</kaphato>
		<kaphato em_IDREF="01" el_IDREF="02">
			<miota>1987-11-21</miota>
		</kaphato>
		<kaphato em_IDREF="01" el_IDREF="03">
			<miota>1987-11-21</miota>
		</kaphato>
		<kaphato em_IDREF="02" el_IDREF="02">
			<miota>1997-12-23</miota>
		</kaphato>
		<kaphato em_IDREF="02" el_IDREF="03">
			<miota>1987-12-24</miota>
		</kaphato>
		<kaphato em_IDREF="03" el_IDREF="03">
			<miota>2001-12-21</miota>
		</kaphato>
		<kaphato em_IDREF="04" el_IDREF="01">
			<miota>1987-06-21</miota>
		</kaphato>
		<kaphato em_IDREF="04" el_IDREF="03">
			<miota>1987-12-30</miota>
		</kaphato>
		<kaphato em_IDREF="05" el_IDREF="01">
			<miota>2011-12-21</miota>
		</kaphato>
		<kaphato em_IDREF="05" el_IDREF="02">
			<miota>2020-12-21</miota>
		</kaphato>
	</kaphatok>
</pizzalanc_nyilvantartas>
