=== leventekeves/IG9GGV_XMLGyak/IG9GGV_1005/KL_konyv.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/KL_konyv" elementFormDefault="qualified">
	<xs:element name="konyvek" >
		<xs:complexType>
			<xs:sequence>
				<xs:element name="konyv" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="cim" type="xs:string"/>
							<xs:element name="kiadasi-ev" type="xs:unsignedShort"/>
							<xs:element name="kiado" type="xs:string"/>
							<xs:element name="szerzo" type="xs:string" maxOccurs="unbounded"/>
							<xs:element name="absztrakt" type="xs:string"/>
						</xs:sequence>
						<xs:attribute name="id" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== leventekeves/IG9GGV_XMLGyak/IG9GGV_1005/KL_konyv.xml
<?xml version="1.0" encoding="UTF-8"?>

<konyvek xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="KL_konyv.xsd">
	<konyv id="k1">
		<cim>Oktatást támogató informatikai rendszerek</cim>
		<kiadasi-ev>2014</kiadasi-ev>
		<kiado>JATEPress</kiado> 
		<szerzo>Goldman Júlia</szerzo>
		<szerzo>Gutai Árpád</szerzo>
		<szerzo>Németh Tamás</szerzo>
		<szerzo>Sárkány Rita</szerzo>
		<absztrakt>1</absztrakt>
	</konyv>
	<konyv id="k2">
		<cim>Gyors kontextusalapú tervezés - A felhasználó-központú tervezés technikájának gyakorlati kalauza</cim>
		<kiadasi-ev>2010</kiadasi-ev>
		<kiado>Akadémiai Kiadó</kiado>
		<szerzo>Karen Holtzblatt</szerzo>
		<szerzo>Jessamyn Burns Wendell</szerzo>
		<absztrakt>2</absztrakt>
	</konyv>
	<konyv id="k3">
		<cim>Fordítóprogramok szerkesztése Flex és Bison segítségével</cim>
		<kiadasi-ev>2014</kiadasi-ev>
		<kiado>Erdélyi Múzeum-Egyesület</kiado>
		<szerzo>Bodó Zalán</szerzo>
		<absztrakt>Jelen jegyzet négy fő fejezetből áll. Az 1. fejezet bevezetőt nyújt a formális nyelvek és fordítóprogramok elméletébe, ismertetve a jegyzet további részeinek megértéséhez szükséges fogalmakat. Így bemutatásra kerülnek a generatív nyelvtanok, véges automaták, reguláris kifejezések, veremautomaták, illetve a fordítóprogramok a lexikális, szintaktikai, szemantikai elemzések, a kódgenerálás és kódoptimalizálás témakörének rövid ismertetésével. A 2. fejezet a lexikális elemzésben használt Flex eszközt mutatja be, ismertetve a leíró fájlok felépítését, a rendelkezésünkre álló reguláris kifejezéseket, illetve a Flexet vezérlő illesztési mechanizmust. A 3. fejezet a Bisonról szól, amit szintaktikai és szemantikai elemző generálásra, illetve kódgenerálásra használhatunk. A 4. fejezet a Flex és a Bison együttes működését hivatott bemutatni példákon keresztül, illetve azt, hogy hogyan tudunk saját fordítóprogramot szerkeszteni ezen eszközök és a Netwide Assembler segítségével.</absztrakt>
	</konyv>
</konyvek>
